---
- name: Set root password
  user:
    name: root
    password: "{{ ROOT_PASSWORD | password_hash('sha512') }}"

- name: Set oracle user password
  user:
     name: oracle
     password: "{{ ORACLE_PASSWORD  | password_hash('sha512') }}"

- name: Change ownership of /u01 to oracle user
  file:
    path: /u01
    state: directory
    owner: oracle
    group: oinstall
    mode: '0775'
    recurse: yes
