---
- name: Update Linux OS
  hosts: all
  become: yes
  tasks:
    - name: Update all packages to the latest version
      yum:
        name: "*"
        state: latest

    - name: Clean up yum cache (for RHEL/CentOS/Fedora-based systems)
      yum:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Check if a reboot is required (RHEL/CentOS)
      shell: needs-restarting -r
      register: reboot_check
      failed_when: reboot_check.rc not in [0, 1]
      when: ansible_os_family == "RedHat"
    
    - name: Reboot the system if updates require it (RHEL/CentOS)
      reboot:
        msg: "Rebooting after updates on RHEL/CentOS"
        reboot_timeout: 600
      when: reboot_check.rc == 1
