---
#- name: restart network
#  systemd:
#    name: network
#    state: restarted
#    enabled: yes
- name: wait for network to come up
  wait_for:
    host: "{{ new_ip }}"
    port: 22
    delay: 10
    timeout: 60