- name: Create ASM Disk Groups
  become: yes
  become_user: grid
  shell: |
    . /home/grid/profile_asm.sh
    sqlplus / as sysasm <<EOF
    CREATE DISKGROUP data EXTERNAL REDUNDANCY DISK '/dev/oracleasm/asm-data-disk1'
           ATTRIBUTE 'compatible.asm'='19.0','compatible.rdbms'='19.0';
    CREATE DISKGROUP reco EXTERNAL REDUNDANCY DISK '/dev/oracleasm/asm-reco-disk1'
           ATTRIBUTE 'compatible.asm'='19.0','compatible.rdbms'='19.0';
    SET LINESIZE 100
    COLUMN name FORMAT A30
    SELECT name, compatibility FROM v\$asm_diskgroup ORDER BY name;
    EXIT;
    EOF
  register: asm_diskgroup_output

- name: Display ASM Disk Group Creation Output
  debug:
    var: asm_diskgroup_output.stdout_lines
- name: Check cluster configuration
  shell: "{{ grid_home }}/bin/crsctl stat res -t"
  register: cluster_status_output
- name: Display Cluster Configuration Output
  debug:
    var: cluster_status_output.stdout_lines