DOMAIN_NAME: "scslabs.com"
ORACLE_TERM: "xterm"
GRID_SOFTWARE: LINUX.X64_193000_grid_home.zip
oracle_user:                     "oracle"
software_dir: "/u01/stage" 
oracle_install_group:            "oinstall"
root_dir:                        "/u01"
stage_dir:                       "/u01/stage"
grid_home: /u01/app/product/grid/19.3.0
grid_base: /u01/app/grid
asmi_name: "+ASM"
ASMI: "+ASM"
gridsetup_installer:              "{{ grid_home }}/gridSetup.sh"
gi_rspfile:  gridsetup19c.rsp
grid_user: grid
root_user: root
ora_inventory: /u01/app/oraInventory
ora_language:      en
install_option:     HA_CONFIG 
oracle_base:        /u01/app/grid
oracle_home:        /u01/app/product/grid/19.3.0
dba_grp: asmdba
oper_grp: asmoper
osasm_grp: asmadmin
node_fq_hostname:      "osiasmdb01.scslabs.com"
storage_Option:        ASM
dg_name:               CRS
dg_redundancy:         EXTERNAL
ignore_DownNodes:       false
mgt_Option:             NONE
oms_Port:               0
execute_RootScript:     false
asmdiskpre:            /dev/oracleasm/disks/ASM_DISK0
asmdiskGroupdisks:      '/dev/oracleasm/asm-crs1,/dev/oracleasm/asm-data1,/dev/oracleasm/asm-fra1'
asmdiskDiscoveryString: "/dev/oracleasm/disks"
disk_discstr: "/dev/oracleasm/disks/*"
disk_device1: "/dev/sdb"
pv_name1: "/dev/sdb1"
vg_name1: "grid_vg"
lv_name1: "grid_lv"
mount_point1: "/u01"
fs_type: "xfs"