- name: Display initial configuration message
  debug:
    msg: "*******************************\nConfigure shared disks. {{ ansible_date_time.iso8601 }}\n********************************************"

- name: Partition disks
  shell: echo -e "n\np\n1\n\n\nw" | fdisk /dev/{{ item }}
  args:
    creates: "/dev/{{ item }}1" 
  with_items:
    - sdg
  notify:
    - run partprobe

- name: Display partitioned disks
  command: ls /dev/sd*
  register: disk_list
  changed_when: false
  failed_when: false

- name: Verify partition creation
  command: lsblk -o NAME,SIZE,TYPE,MOUNTPOINT
  register: lsblk_output

- name: Show partition output
  debug:
    var: lsblk_output.stdout_lines

- name: Configure udev configuration file
  copy:
    dest: /etc/scsi_id.config
    content: |
      options=-g
    owner: root
    group: root
    mode: '0644'

- name: Generate scsi_id for ASM disks
  shell: /usr/lib/udev/scsi_id -g -u -d /dev/{{ item }}
  register: scsi_ids
  loop:
    - sdd
    - sde
    - sdf
    - sdg
  when: ansible_facts.devices[item].partitions is defined

- name: Set ASM disk variables
  set_fact:
    asm_disk1: "{{ scsi_ids.results[0].stdout }}"
    asm_disk2: "{{ scsi_ids.results[1].stdout }}"
    asm_disk3: "{{ scsi_ids.results[2].stdout }}"
    asm_disk4: "{{ scsi_ids.results[3].stdout }}"

- name: Create Oracle ASM udev rules file
  copy:
    dest: /etc/udev/rules.d/99-oracle-asmdevices.rules
    content: |
      KERNEL=="sd?1", SUBSYSTEM=="block", PROGRAM=="/usr/lib/udev/scsi_id -g -u -d /dev/$parent", RESULT=="{{ asm_disk1 }}", SYMLINK+="oracleasm/asm-crs-disk1", OWNER="grid", GROUP="asmadmin", MODE="0660"
      KERNEL=="sd?1", SUBSYSTEM=="block", PROGRAM=="/usr/lib/udev/scsi_id -g -u -d /dev/$parent", RESULT=="{{ asm_disk2 }}", SYMLINK+="oracleasm/asm-data-disk1", OWNER="grid", GROUP="asmadmin", MODE="0660"
      KERNEL=="sd?1", SUBSYSTEM=="block", PROGRAM=="/usr/lib/udev/scsi_id -g -u -d /dev/$parent", RESULT=="{{ asm_disk3 }}", SYMLINK+="oracleasm/asm-reco-disk1", OWNER="grid", GROUP="asmadmin", MODE="0660"
      KERNEL=="sd?1", SUBSYSTEM=="block", PROGRAM=="/usr/lib/udev/scsi_id -g -u -d /dev/$parent", RESULT=="{{ asm_disk4 }}", SYMLINK+="oracleasm/asm-reco-disk2", OWNER="grid", GROUP="asmadmin", MODE="0660"  
- name: Run partprobe for all disks
  command: "/sbin/partprobe /dev/{{ item }}1"
  loop:
    - sdd
    - sde
    - sdf
    - sdg
  register: partprobe_results
  ignore_errors: yes

- name: Run udevadm control --reload-rules
  shell: /sbin/udevadm control --reload-rules

- name: Run partprobe again after reloading udev rules
  command: "/sbin/partprobe /dev/{{ item }}1"
  loop:
    - sdd
    - sde
    - sdf
    - sdg
  register: partprobe_results_2
  ignore_errors: yes

- name: Reload udev rules again
  command: /sbin/udevadm control --reload-rules

- name: List Oracle ASM disk symlinks
  command: "ls -ltr /dev/oracleasm/*"
  register: asm_symlinks
  changed_when: false
  failed_when: false

- name: Show Oracle ASM symlinks
  debug:
    var: asm_symlinks.stdout_lines  