---
- name: Create Oracle Database using DBCA
  become: yes
  become_user: oracle
  shell: >
    {{ oracle_home }}/bin/dbca -silent -createDatabase
    -templateName General_Purpose.dbc
    -gdbname {{ oracle_unqname }} -responseFile NO_VALUE
    -characterSet AL32UTF8
    -sysPassword {{ SYS_PASSWORD }}
    -systemPassword {{ SYS_PASSWORD }}
    -createAsContainerDatabase true
    -numberOfPDBs 1
    -pdbName {{ pdb_name }}
    -pdbAdminPassword {{ SYS_PASSWORD }}
    -databaseType MULTIPURPOSE
    -automaticMemoryManagement false
    -totalMemory 1024
    -redoLogFileSize 50
    -emConfiguration NONE
    -ignorePreReqs
    -storageType ASM
    -diskGroupName +DATA
    -recoveryGroupName +RECO
    -useOMF true
    -asmsnmpPassword {{ SYSASMPassword }}
  register: dbca_output
- name: Check DBCA output
  debug:
    var: dbca_output.stdout_lines