---
- name: Create environment script
  copy:
    dest: "/home/oracle/profile_oracle.sh"
    content: |
      # Regular settings.
      export TMP=/tmp
      export TMPDIR=$TMP
      export ORACLE_HOSTNAME={{ node_fq_hostname }}
      export ORACLE_BASE={{ oracle_base }}
      export ORACLE_HOME={{ oracle_home }}
      export ORACLE_SID={{ oracle_sid }}
      export PATH=/usr/sbin:/usr/local/bin:$PATH
      export PATH=$ORACLE_HOME/bin:$PATH
      export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib
      export CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib
      export ORA_INVENTORY={{ ora_inventory }}

- name: Add environment script to .bash_profile
  lineinfile:
    path: /home/oracle/.bash_profile
    line: ". /home/oracle/profile_oracle.sh"
    state: present
- name: Change ownership of scripts directory
  file:
    path: "/home/oracle"
    owner: oracle
    group: oinstall
    recurse: yes