---
- name: Create ASM groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - asmadmin
    - asmdba
    - asmoper

- name: Create user grid
  user:
    name: grid
    state: present
    group: oinstall
    groups:
      - asmadmin
      - asmdba
      - asmoper
    shell: /bin/bash
    create_home: yes
    comment: "Grid User for Oracle ASM"

- name: Append asmdba and asmadmin to oracle user
  user:
    name: oracle
    groups:
      - asmdba
      - asmadmin
    append: yes