---
#- name: Backup the original network configuration file
#  copy:
#    src: "/etc/sysconfig/network-scripts/ifcfg-{{ interface }}"
#    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ interface }}.bak"
#    backup: yes
#  when: ansible_facts['os_family'] == "RedHat"
#
#- name: Change IP address in network configuration file
#  lineinfile:
#    path: "/etc/sysconfig/network-scripts/ifcfg-{{ interface }}"
#    regexp: '^IPADDR'
#    line: "IPADDR={{ new_ip }}"
#  notify:
#    - restart network
#
#- name: Change netmask in network configuration file
#  lineinfile:
#    path: "/etc/sysconfig/network-scripts/ifcfg-{{ interface }}"
#    regexp: '^NETMASK'
#    line: "NETMASK={{ new_netmask }}"
#  notify:
#    - restart network
#
#- name: Change gateway in network configuration file
#  lineinfile:
#    path: "/etc/sysconfig/network-scripts/ifcfg-{{ interface }}"
#    regexp: '^GATEWAY'
#    line: "GATEWAY={{ new_gateway }}"
#  notify:
#    - restart network

- name: Set DNS servers
  blockinfile:
    path: "/etc/resolv.conf"
    block: |
      nameserver {{ dns_servers }}
    create: yes
    mode: '0644'

- name: Restart network to apply changes
  systemd:
    name: network
    state: restarted
    enabled: yes
  notify:
    - wait for network to come up

