---
- name: Set the system hostname
  command: hostnamectl set-hostname "{{ node_fq_hostname }}"
- name: Update /etc/hostname file
  copy:
    dest: /etc/hostname
    content: "{{ node_fq_hostname }}"
    owner: root
    group: root
    mode: '0644'
- name: Reboot to apply the hostname change
  reboot:
    msg: "Rebooting to apply hostname changes"
    reboot_timeout: 300
    test_command: whoami
